export interface Metas {
  ASTRO: number
  BETPLAY: number
  CHANCE: number
  CHANCE_MILLONARIO: number
  DOBLECHANCE: number
  GANE5: number
  GIROS: number
  LOGINS: number
  LOTERIA_FISICA: number
  LOTERIA_VIRTUAL: number
  PAGAMAS: number
  PAGATODO: number
  PATA_MILLONARIA: number
  PROMEDIO_DIARIO_ASTRO: number
  PROMEDIO_DIARIO_BETPLAY: number
  PROMEDIO_DIARIO_CHANCE: number
  PROMEDIO_DIARIO_CHMILL: number
  PROMEDIO_DIARIO_DOBLECHANCE: number
  PROMEDIO_DIARIO_GANE5: number
  PROMEDIO_DIARIO_GIRO
  PROMEDIO_DIARIO_LF: number
  PROMEDIO_DIARIO_LV: number
  PROMEDIO_DIARIO_PAGAMAS: number
  PROMEDIO_DIARIO_PAGATODO: number
  PROMEDIO_DIARIO_PATAMI: number
  PROMEDIO_DIARIO_RECARGAS: number
  PROMEDIO_DIARIO_RECAUDO: number
  PROMEDIO_DIARIO_SOAT: number
  RECARGAS: number
  RECAUDOS: number
  SOAT: number
}
